<?php
require_once __DIR__ . '/../bootstrap.php';
$pdo = db(); $id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT) ?: null; $method = $_SERVER['REQUEST_METHOD'];
if (!in_array(current_user()['role_name'], ['ADMIN', 'HR'], true)) api_response(['error' => 'HR authorization required.'], 403);
if ($method === 'GET') {
    if ($id) { $statement = $pdo->prepare('SELECT e.*, d.name AS department_name, p.name AS position_name, b.name AS branch_name FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN positions p ON p.id=e.position_id LEFT JOIN branches b ON b.id=e.branch_id WHERE e.id=?'); $statement->execute([$id]); $employee = $statement->fetch(); if (!$employee) api_response(['error' => 'Employee not found.'], 404); api_response(['data' => $employee]); }
    api_response(['data' => $pdo->query('SELECT e.*, d.name AS department_name, p.name AS position_name, b.name AS branch_name FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN positions p ON p.id=e.position_id LEFT JOIN branches b ON b.id=e.branch_id ORDER BY e.last_name,e.first_name')->fetchAll()]);
}
if (!in_array($method, ['POST','PUT'], true) || !in_array(current_user()['role_name'], ['ADMIN','HR'], true)) api_response(['error' => 'Method not allowed.'], 405);
$input = api_input(); verify_csrf(); $required = ['employee_number','first_name','last_name']; foreach ($required as $field) if (empty($input[$field])) api_response(['error' => "{$field} is required."], 422);
$values = [$input['employee_number'], $input['first_name'], $input['middle_name'] ?? null, $input['last_name'], $input['suffix'] ?? null, $input['date_of_birth'] ?? null, $input['gender'] ?? null, $input['civil_status'] ?? null, $input['email'] ?? null, $input['phone'] ?? null, $input['address'] ?? null, $input['department_id'] ?? null, $input['position_id'] ?? null, $input['branch_id'] ?? null, $input['employment_status'] ?? 'Active', $input['date_hired'] ?? null, $input['employment_type'] ?? 'Regular'];
try { if ($method === 'POST') { $pdo->prepare('INSERT INTO employees (employee_number,first_name,middle_name,last_name,suffix,date_of_birth,gender,civil_status,email,phone,address,department_id,position_id,branch_id,employment_status,date_hired,employment_type) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($values); $newId=(int)$pdo->lastInsertId(); audit('CREATE','employees',$newId); api_response(['data' => ['id' => $newId]], 201); } if (!$id) api_response(['error' => 'Employee ID is required.'], 422); $beforeStmt = $pdo->prepare('SELECT * FROM employees WHERE id=?'); $beforeStmt->execute([$id]); $before = $beforeStmt->fetch() ?: null; $pdo->prepare('UPDATE employees SET employee_number=?,first_name=?,middle_name=?,last_name=?,suffix=?,date_of_birth=?,gender=?,civil_status=?,email=?,phone=?,address=?,department_id=?,position_id=?,branch_id=?,employment_status=?,date_hired=?,employment_type=? WHERE id=?')->execute([...$values,$id]); audit('UPDATE','employees',$id); notify_employee_saved($pdo, $id, $before); api_response(['data' => ['id' => $id]]); } catch (PDOException $exception) { api_response(['error' => 'Could not save employee.'], 422); }