<?php
require_once __DIR__ . '/../config/config.php';
require_roles(['ADMIN', 'HR']);
$definitions = ['departments' => ['label' => 'Departments', 'table' => 'departments', 'extra' => 'description', 'title' => 'Department'], 'positions' => ['label' => 'Positions', 'table' => 'positions', 'extra' => 'description', 'title' => 'Position'], 'branches' => ['label' => 'Branches', 'table' => 'branches', 'extra' => 'address', 'title' => 'Branch']];
$type = $_GET['type'] ?? 'departments'; if (!isset($definitions[$type])) { http_response_code(404); exit('Master data type not found.'); }
$definition = $definitions[$type]; $pdo = db(); $editId = filter_input(INPUT_GET, 'edit', FILTER_VALIDATE_INT) ?: null; $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $formAction = $_POST['form_action'] ?? 'save'; $recordId = (int) ($_POST['id'] ?? 0); $name = trim((string) ($_POST['name'] ?? '')); $extra = post_value('extra');
    try {
        if ($formAction === 'delete') { $pdo->prepare("DELETE FROM {$definition['table']} WHERE id=?")->execute([$recordId]); audit('DELETE', $type, $recordId); flash('success', $definition['title'] . ' deleted.'); }
        elseif ($name === '') $error = $definition['title'] . ' name is required.';
        elseif ($recordId) { $pdo->prepare("UPDATE {$definition['table']} SET name=?, {$definition['extra']}=? WHERE id=?")->execute([$name, $extra, $recordId]); audit('UPDATE', $type, $recordId); flash('success', $definition['title'] . ' updated.'); }
        else { $pdo->prepare("INSERT INTO {$definition['table']} (name, {$definition['extra']}) VALUES (?, ?)")->execute([$name, $extra]); $newId = (int) $pdo->lastInsertId(); audit('CREATE', $type, $newId); flash('success', $definition['title'] . ' created.'); }
        if (!$error) redirect('admin/' . $type . '.php');
    } catch (PDOException $exception) { $error = 'That name already exists or the record is in use.'; }
}
$edit = null; if ($editId) { $statement = $pdo->prepare("SELECT * FROM {$definition['table']} WHERE id=?"); $statement->execute([$editId]); $edit = $statement->fetch(); }
$records = $pdo->query("SELECT * FROM {$definition['table']} ORDER BY name")->fetchAll(); $pageTitle = $definition['label']; require __DIR__ . '/../includes/header.php';
?><div class="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-8"><div><p class="text-sm text-slate-500">Controlled reference data</p><h1 class="font-display text-3xl font-bold mt-1"><?= e($definition['label']) ?></h1></div><a href="?type=<?= e($type) ?>#form" class="rounded-lg bg-teal-700 px-5 py-3 text-sm font-bold text-white">+ Add <?= e(strtolower($definition['title'])) ?></a></div><?php if ($error): ?><div class="mb-6 rounded-lg bg-red-50 border border-red-200 p-3 text-sm text-red-700"><?= e($error) ?></div><?php endif; ?><div class="grid xl:grid-cols-[1fr_360px] gap-6"><section class="bg-white border border-slate-200 rounded-xl overflow-x-auto"><table class="w-full text-left text-sm"><thead class="text-xs uppercase text-slate-400 bg-slate-50"><tr><th class="px-6 py-4">Name</th><th class="px-6 py-4"><?= e(ucfirst($definition['extra'])) ?></th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach ($records as $record): ?><tr><td class="px-6 py-4 font-bold"><?= e($record['name']) ?></td><td class="px-6 py-4 text-slate-500"><?= e($record[$definition['extra']] ?? '—') ?></td><td class="px-6 py-4"><span class="text-xs font-bold text-emerald-700">Active</span></td><td class="px-6 py-4 text-right"><a href="?type=<?= e($type) ?>&edit=<?= e($record['id']) ?>#form" class="font-bold text-teal-700">Edit</a><form class="inline" method="post"><?= csrf_field() ?><input type="hidden" name="form_action" value="delete"><input type="hidden" name="id" value="<?= e($record['id']) ?>"><button data-confirm="Delete this record?" class="ml-4 font-bold text-red-600">Delete</button></form></td></tr><?php endforeach; ?></tbody></table><?php if (!$records): ?><p class="p-10 text-center text-slate-500">No records yet.</p><?php endif; ?></section><section id="form" class="bg-white border border-slate-200 rounded-xl p-6 h-fit"><h2 class="font-display text-xl font-bold"><?= $edit ? 'Edit' : 'Add' ?> <?= e($definition['title']) ?></h2><form method="post" class="mt-5 space-y-4"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($edit['id'] ?? '') ?>"><label class="block text-sm font-semibold">Name<input required name="name" value="<?= e($edit['name'] ?? '') ?>" class="field"></label><label class="block text-sm font-semibold"><?= e(ucfirst($definition['extra'])) ?><textarea name="extra" rows="3" class="field"><?= e($edit[$definition['extra']] ?? '') ?></textarea></label><button class="w-full rounded-lg bg-teal-700 px-5 py-3 text-sm font-bold text-white"><?= $edit ? 'Update' : 'Create' ?> <?= e($definition['title']) ?></button></form></section></div><?php require __DIR__ . '/../includes/footer.php';